### ISSUE TITLE
Create a docker image for redshift_console

### ISSUE THREAD

**Issue by michaelloewenstein** [EverythingMe/redshift_console#13]

**Comment by arikfr** [comment]
I've created on based on the `python:2.7` base image: https://github.com/EverythingMe/redshift_console/commit/f5b522d2d45aed6e5f1f03283240974eff7e9e66

It's my first docker container, so feedback is appreciated.

To run it use:

``` bash
docker run -e REDSHIFT_CONNECTION_STRING="user= password= host= port=5439 dbname=" -p 5000:5000 arikfr/redshift-console
```

**Comment by michaelloewenstein** [comment]
The container works great, very easy to run this way thanks !
Although there are some issues with the app itself:
1.The Schemas page doesn't show any data (besides the upper tool bar)
2. On the Chrome I have to hit the restart button in order to see data (Loads, Status) . in Safari no refresh is needed. 

Just saw this on the schemas page:

Uncaught (in promise) TypeError: Cannot read property 'toFixed' of undefined
    at n.createClass.render (http://192.168.99.102:5000/scripts/app.js:9:26750)
    at N._renderValidatedComponentWithoutOwnerOrContext (http://192.168.99.102:5000/scripts/app.js:3:6370)
    at N._renderValidatedComponent (http://192.168.99.102:5000/scripts/app.js:3:6625)
    at r.measure.i [as _renderValidatedComponent](http://192.168.99.102:5000/scripts/app.js:5:6210)
    at N.mountComponent (http://192.168.99.102:5000/scripts/app.js:3:536)
    at r.measure.i [as mountComponent](http://192.168.99.102:5000/scripts/app.js:5:6210)
    at Object.i.mountComponent (http://192.168.99.102:5000/scripts/app.js:5:12153)
    at i.m.Mixin.mountChildren (http://192.168.99.102:5000/scripts/app.js:5:2063)
    at i.Mixin._createContentMarkup (http://192.168.99.102:5000/scripts/app.js:3:15059)
    at i.Mixin.mountComponent (http://192.168.99.102:5000/scripts/app.js:3:14228)
    at Object.i.mountComponent (http://192.168.99.102:5000/scripts/app.js:5:12153)

**Comment by arikfr** [comment]
Re. schemas page -- I'll check why this happens & fix.

Re. the need to refresh - what version of Chrome are you using? What OS? Are there any other errors in the console on those pages?

**Comment by michaelloewenstein** [comment]
Chrome - I go to one of the tabs (status,loads) - there is an error and the page doesn't load, I hit refresh - no error and the page loads. 
This happens only after I visit the schemas tab, I think solving the schemas problem will solve this one.

## Chrome Version 43.0.2357.130 (64-bit)

app.js:5 Uncaught TypeError: Cannot read property '_currentElement' of null
Uncaught TypeError: Cannot read property '_currentElement' of nulli.unmountComponent @ app.js:5N.unmountComponent @ app.js:3i.unmountComponent @ app.js:5i.unmountChildren @ app.js:2m.Mixin.unmountChildren @ app.js:5i.Mixin.unmountComponent @ app.js:3i.unmountComponent @ app.js:5N.unmountComponent @ app.js:3i.unmountComponent @ app.js:5N.unmountComponent @ app.js:3i.unmountComponent @ app.js:5N.unmountComponent @ app.js:3i.unmountComponent @ app.js:5N.unmountComponent @ app.js:3i.unmountComponent @ app.js:5i.unmountChildren @ app.js:2m.Mixin.unmountChildren @ app.js:5i.Mixin.unmountComponent @ app.js:3i.unmountComponent @ app.js:5N.unmountComponent @ app.js:3i.unmountComponent @ app.js:5i.unmountChildren @ app.js:2m.Mixin.unmountChildren @ app.js:5i.Mixin.unmountComponent @ app.js:3i.unmountComponent @ app.js:5N.unmountComponent @ app.js:3i.unmountComponent @ app.js:5N.unmountComponent @ app.js:3i.unmountComponent @ app.js:5N._updateRenderedComponent @ app.js:3N._performComponentUpdate @ app.js:3N.updateComponent @ app.js:3i @ app.js:5N.receiveComponent @ app.js:3i.receiveComponent @ app.js:5N._updateRenderedComponent @ app.js:3N._performComponentUpdate @ app.js:3N.updateComponent @ app.js:3i @ app.js:5N.receiveComponent @ app.js:3i.receiveComponent @ app.js:5i.updateChildren @ app.js:2m.Mixin._updateChildren @ app.js:5m.Mixin.updateChildren @ app.js:5i.Mixin._updateDOMChildren @ app.js:3i.Mixin.updateComponent @ app.js:3i.Mixin.receiveComponent @ app.js:3i.receiveComponent @ app.js:5N._updateRenderedComponent @ app.js:3N._performComponentUpdate @ app.js:3N.updateComponent @ app.js:3i @ app.js:5N.receiveComponent @ app.js:3i.receiveComponent @ app.js:5i.updateChildren @ app.js:2m.Mixin._updateChildren @ app.js:5m.Mixin.updateChildren @ app.js:5i.Mixin._updateDOMChildren @ app.js:3i.Mixin.updateComponent @ app.js:3i.Mixin.receiveComponent @ app.js:3i.receiveComponent @ app.js:5N._updateRenderedComponent @ app.js:3N._performComponentUpdate @ app.js:3N.updateComponent @ app.js:3i @ app.js:5N.receiveComponent @ app.js:3i.receiveComponent @ app.js:5N._updateRenderedComponent @ app.js:3N._performComponentUpdate @ app.js:3N.updateComponent @ app.js:3i @ app.js:5N.receiveComponent @ app.js:3i.receiveComponent @ app.js:5N._updateRenderedComponent @ app.js:3N._performComponentUpdate @ app.js:3N.updateComponent @ app.js:3i @ app.js:5N.receiveComponent @ app.js:3i.receiveComponent @ app.js:5N.performUpdateIfNecessary @ app.js:3i.performUpdateIfNecessary @ app.js:5s @ app.js:5o.perform @ app.js:6o.perform @ app.js:6v.perform @ app.js:5w @ app.js:5i @ app.js:5o.closeAll @ app.js:6o.perform @ app.js:6p.batchedUpdates @ app.js:3u @ app.js:5r @ app.js:5f.enqueueElementInternal @ app.js:5(anonymous function) @ app.js:4Q.scrollMonitor @ app.js:4Q._updateRootComponent @ app.js:4Q.render @ app.js:4i @ app.js:5(anonymous function) @ app.js:1A @ app.js:8(anonymous function) @ app.js:8(anonymous function) @ app.js:8r.to @ app.js:8(anonymous function) @ app.js:8(anonymous function) @ app.js:8(anonymous function) @ app.js:8r.from @ app.js:8l.createClass.statics.dispatch @ app.js:8l.createClass.statics.handleLocationChange @ app.js:8(anonymous function) @ app.js:8r @ app.js:8a @ app.js:8

**Comment by michaelloewenstein** [comment]
Any news regarding schemas issue ?

**Comment by arikfr** [comment]
I couldn't reproduce it locally, but I just put a "safe guard" around the toFixed calls that might fail. I'll push the fix and release an updated version of the pip package and docker container tomorrow.

**Comment by michaelloewenstein** [comment]
Great

**Comment by arikfr** [comment]
@michaelloewenstein can you try pulling new version of the docker image and see if this resolved for you?

**Comment by arikfr** [comment]
@michaelloewenstein if you didn't pull it already, please pull `everythingme/redshift_console` -- I'm going to deprecate the arikfr one.

**Comment by michaelloewenstein** [comment]
Looking good, thanks! I'll try to use it a bit before we close this issue.

_Michael Loewenstein_
http://www.facebook.com/LoenMichael
http://il.linkedin.com/pub/michael-loewenstein/22/9a5/713/ | Blog
http://blogs.microsoft.co.il/miziel |w: i-collect.info | m:+972544503551 |
 e:Michael.Loewenstein@gmail.com

**Comment by arikfr** [comment]
Actually this one is already closed ;-) But feel free to open new issues if you stumble at anything.

**Comment by michaelloewenstein** [comment]
Out of the 6 tables I got in some schema, 2 of them appears to be empty
while they are not empty in reality !  ever ran into something like that?
In the attached image you can see the redshift-console above and the sql
client below providing different insights.
[image: Inline image 1]

_Michael Loewenstein_
http://www.facebook.com/LoenMichael
http://il.linkedin.com/pub/michael-loewenstein/22/9a5/713/ | Blog
http://blogs.microsoft.co.il/miziel |w: i-collect.info | m:+972544503551 |
 e:Michael.Loewenstein@gmail.com

**Comment by arikfr** [comment]
It doesn't show the image, can you attach it through GitHub's interface, or just send me directly (arik@everything.me)? thanks.

**Comment by michaelloewenstein** [comment]
In addition, there is a table that exists but doesn't appear at all!

_Michael Loewenstein_
http://www.facebook.com/LoenMichael
http://il.linkedin.com/pub/michael-loewenstein/22/9a5/713/ | Blog
http://blogs.microsoft.co.il/miziel |w: i-collect.info | m:+972544503551 |
 e:Michael.Loewenstein@gmail.com

**Comment by arikfr** [comment]
The missing table: is it on the same DB you used in the connection string? Maybe permissions problem? (or you've used a superuser?)
