### ISSUE TITLE
Can't run redshift_console

### ISSUE THREAD

**Issue by michaelloewenstein** [EverythingMe/redshift_console#14]
setup.py install fails: 
 File "setup.py", line 7, in <module>
    install_reqs = parse_requirements('requirements.txt', session=pip.download.PipSession())
AttributeError: 'module' object has no attribute 'PipSession'

I tried to remov the following: " , session=pip.download.PipSession() " and got a different error when trying to run redshift-console runserver: 

 File "/usr/lib/python2.6/site-packages/redshift_console-0.1.1-py2.6.egg/redshift_console/redshift.py", line 178
    self.inflight_queries = {q['id']: q for q in _concat_query_text(inflight_queries)}

**Comment by arikfr** [comment]
What version of pip do you have? What version of Python?

**Comment by michaelloewenstein** [comment]
pip 1.3.1 from /usr/lib/python2.6/site-packages (python 2.6)

running inside a centos6 docker container

_Michael Loewenstein_
http://www.facebook.com/LoenMichael
http://il.linkedin.com/pub/michael-loewenstein/22/9a5/713/ | Blog
http://blogs.microsoft.co.il/miziel |w: i-collect.info | m:+972544503551 |
 e:Michael.Loewenstein@gmail.com

**Comment by arikfr** [comment]
I think this feature needs newer version of `pip`. If having the container based on centos is not a requirement, you can use the container I created:

https://registry.hub.docker.com/u/arikfr/redshift-console/

(based on the python:2.7 base image)

**Comment by arikfr** [comment]
@michaelloewenstein can I close this?

**Comment by michaelloewenstein** [comment]
Yes
