### ISSUE TITLE
Multiple sorting keys appears as a single sorting key

### ISSUE THREAD

**Issue by michaelloewenstein** [EverythingMe/redshift_console#18]
Given a table with multiple sorting keys, only a single sort key is presented.

**Comment by arikfr** [comment]
Anything special about this keys? Are these interleaved sorting keys?

**Comment by michaelloewenstein** [comment]
Nothing special, a table with tow sort keys.
The second sort key ( has the value '2' on 'sortkey' column on pg_table_def
) gets a 'No' value on the redshift console 'Sort Key' column.

_Michael Loewenstein_
http://www.facebook.com/LoenMichael
http://il.linkedin.com/pub/michael-loewenstein/22/9a5/713/ | Blog
http://blogs.microsoft.co.il/miziel |w: i-collect.info | m:+972544503551 |
 e:Michael.Loewenstein@gmail.com

**Comment by arikfr** [comment]
Apparently they changed the response format (before it was true/false). I'll fix this. Thanks.

**Comment by arikfr** [comment]
While it's closed, PyPI and docker were not updated. I've will write here once they do.

**Comment by arikfr** [comment]
Updated (both PyPI and docker).

**Comment by michaelloewenstein** [comment]
Nice !
