### ISSUE TITLE
python site package does not include index.html

### ISSUE THREAD

**Issue by Liorba** [EverythingMe/redshift_console#26]
after cloning the repo and run setup.py ,runt the runserver command I got the following error:

No such file or directory: '/Library/Python/2.7/site-packages/redshift_console-0.1.3-py2.7.egg/redshift_console/static/dist/index.html'

after little examination I found that the 'static' folder is not found in python site packages, moreover index.html is actually found in static/app and not in static/dist like the error mention

**Comment by orenitamar** [comment]
Thanks Lior. 
I managed to reproduce what you are describing regarding the missing static dir after running setup.py, working on a fix.

Please note that index.html exists both in app and dist.

**Comment by arikfr** [comment]
If you just clone the repo, then you need to build the static assets yourself (run `gulp build`, for which you need to install NodeJS and required packages).

When packaging the project for PyPi we run `gulp build` and create a distribution that includes the `dist` folder.

If you don't intend to develop the project, then you can simply run `pip install redshift-console` (or use the docker image), which includes everything you need to run the project.

If you plan on developing, then you need to install required dependencies. You can check the `Makefile` for a point of reference.

**Comment by Liorba** [comment]
At first I tried to run pip install and got this error ...
it seems that setup.py does not copy the "static" folder to
 /Library/Python/2.7/site-packages/redshift_console

then I clone the repo and run `python setup.py install`
and it didn't help. 

Finally I tried to copy the static folder to /Library/Python/2.7/site-packages/redshift_console 
but with no luck :(

**Comment by arikfr** [comment]
I just created an empty virtualenv and ran `pip install redshift-console`, it installed version 0.1.3 and the package folder includes the `static/dist` folder.

Can you elaborate on how you installed it, and what environment (OS, Python version, pip version)?

**Comment by Liorba** [comment]
`sudo pip install redshift-console`
and then 
`redshift-console runserver`
when I open the browser on localhost:5000
OS mac os
Python 2.7.10
pip version 7.1.2

**Comment by arikfr** [comment]
Closing as can't be reproduced.
